version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./integration/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080/tcp
    command:
      - start-dev
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
  grafana:
    container_name: 'dvelop-odata-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
    ports:
      - 3000:3000/tcp
    environment:
      GF_LOG_LEVEL: 'debug'
    volumes:
      - ./dist:/var/lib/grafana/plugins/dvelop-odata-datasource
      - ./provisioning:/etc/grafana/provisioning
      - ./integration/keycloak/grafana.ini:/etc/grafana/grafana.ini
  test-server:
    build: test-server
    ports:
      - "4004:4004"
