version: '3'
services:
  grafana:
    image: grafana/grafana:9.4.7
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/odata
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=dvelop-odata-datasource
