version: '3.8'

services:
  grafana:
    container_name: 'dvelop-odata-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/odata
      - ./provisioning:/etc/grafana/provisioning
  test-server:
    build: test-server
    ports:
      - "4004:4004"
